/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.geom.AffineTransform;
import java.util.List;
import java.util.Map.Entry;
import modele.Match;
import modele.arbitre.ArbitreLigne;
import modele.personne.Ramasseur;

/**
 *
 * @author dave
 */
public class IHMInfoMatch extends javax.swing.JFrame {

    /**
     * Creates new form IHMInfoMatch
     */
    public IHMInfoMatch(Match match) {
        initComponents();
        
        if (match == null)
            return;
        
        jLabel_Contre.setText("");
        
        
        
        
        
        jLabel_IdMatch.setText(Integer.toString(match.getId()));
        jLabel_Joueur1.setText(match.getEquipe1().toString() + " (" + match.getEquipe1().getNationalite() + ")");
        //jLabel_NationaliteJ1.setText(match.getJoueur1().getNationalite());
        jLabel_Joueur2.setText(match.getEquipe2().toString() + " (" + match.getEquipe2().getNationalite() + ")");
        //jLabel_NationaliteJ2.setText(match.getJoueur2().getNationalite());
        
        if (match.estFini()) {
            if (match.getGagnant() == 1) {
                // équipe 1 a gagné
                jLabel_Joueur1.setText(jLabel_Joueur1.getText() + " (Gagnant)");
                Font font = jLabel_Joueur1.getFont();
                jLabel_Joueur1.setFont(new Font(font.getName(), Font.BOLD, font.getSize()));
                
            }
            else {  // equipe 2 a gagné
                jLabel_Joueur2.setText(jLabel_Joueur2.getText() + " (Gagnant)");
                Font font = jLabel_Joueur2.getFont();
                jLabel_Joueur2.setFont(new Font(font.getName(), Font.BOLD, font.getSize()));
            }
        }
        
        jLabel_Court.setText("Lieu : " + match.getCourt().getNom());
        
        //  Date & heure
        //System.out.println("dateTime=" + match.getCreneau().getDateTime().getDayOfMonth());
        jLabel_Date.setText(match.getCreneau().getDateTime().toString("EEEE dd MMMM YYYY"));
        jLabel_Heure.setText(match.getCreneau().getDateTime().toString("HH:mm"));
        
        //  affichage des arbitres
        
        jLabel_ArbitreChaise.setText(match.getArbitreChaise().toString() + " (" + match.getArbitreChaise().getNationalite() + ")");
        jLabel_ArbitreFilet.setText(match.getArbitreFilet().toString() + " (" + match.getArbitreFilet().getNationalite() + ")");
        
        String arbitresLignes = "";
        
        for (Entry<Integer, ArbitreLigne> e : match.getArbitresLigne().entrySet()) {
            arbitresLignes += "Ligne " + e.getKey() + " : " + e.getValue().toString() + " (" + e.getValue().getNationalite() + ")\n";
            //jTextArea_ArbitresLigne.append("Ligne " + e.getKey() + " : " + e.getValue().toString() + " (" + e.getValue().getNationalite() + ")\n");
        }
        // on enlève le dernier '\n'
        //arbitresLignes.substring(0, arbitresLignes.length() - "\n".length() -1);
        jTextArea_ArbitresLigne.setText(arbitresLignes);
        
        //jLabel_ArbitresLigne.setText(arbitresLignes);
        
        // affichage des ramasseurs
        
        //String ramasseurs = "";
        List<Ramasseur> listeRamasseurs = match.getEquipeRamasseurs().getRamasseurs();
        //for (Ramasseur r : ) {
        for (Ramasseur r : listeRamasseurs.subList(0, 5)) {
            jTextArea_Ramasseurs1.append(r.toString() + " (" + r.getNationalite() + ")\n");
        }
        for (Ramasseur r : listeRamasseurs.subList(6, 11)) {
            jTextArea_Ramasseurs2.append(r.toString() + " (" + r.getNationalite() + ")\n");
        }
        
        
        setTitle("Détails du match n° " + match.getId());
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel_IdMatch = new javax.swing.JLabel();
        jButton_Fermer = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel_Joueur1 = new javax.swing.JLabel();
        jLabel_Contre = new javax.swing.JLabel();
        jLabel_Joueur2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel_ArbitreFilet = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_ArbitreChaise = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_ArbitresLigne = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_Ramasseurs1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_Ramasseurs2 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel_Date = new javax.swing.JLabel();
        jLabel_Heure = new javax.swing.JLabel();
        jButton_InscrireResultatMatch = new javax.swing.JButton();
        jLabel_Court = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel1.setText("Match n°");

        jLabel_IdMatch.setText("jLabel2");

        jButton_Fermer.setText("Fermer la fenêtre");
        jButton_Fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FermerActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_Joueur1.setText("LabelJoueur1");

        jLabel_Contre.setText("Contre");

        jLabel_Joueur2.setText("LabelJoueur2");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_Joueur1)
                            .addComponent(jLabel_Joueur2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_Contre)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Joueur1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_Contre))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Joueur2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel_ArbitreFilet.setText("erreur");

        jLabel2.setText("Arbitres de ligne :");

        jLabel_ArbitreChaise.setText("erreur");

        jLabel3.setText("Arbitre de chaise :");

        jLabel4.setText("Arbitre de filet :");

        jTextArea_ArbitresLigne.setEditable(false);
        jTextArea_ArbitresLigne.setColumns(20);
        jTextArea_ArbitresLigne.setRows(5);
        jScrollPane1.setViewportView(jTextArea_ArbitresLigne);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel_ArbitreChaise)
                    .addComponent(jLabel_ArbitreFilet))
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel_ArbitreChaise))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel_ArbitreFilet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel5.setText("Ramasseurs de balle :");

        jSplitPane1.setDividerLocation(250);
        jSplitPane1.setDividerSize(15);

        jTextArea_Ramasseurs1.setColumns(20);
        jTextArea_Ramasseurs1.setRows(5);
        jScrollPane2.setViewportView(jTextArea_Ramasseurs1);

        jSplitPane1.setLeftComponent(jScrollPane2);

        jTextArea_Ramasseurs2.setEditable(false);
        jTextArea_Ramasseurs2.setColumns(20);
        jTextArea_Ramasseurs2.setRows(5);
        jScrollPane3.setViewportView(jTextArea_Ramasseurs2);

        jSplitPane1.setRightComponent(jScrollPane3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel6.setText("Date :");

        jLabel8.setText("Heure :");

        jLabel_Date.setText("0");

        jLabel_Heure.setText("0");

        jButton_InscrireResultatMatch.setText("Inscrire le résultat du match");
        jButton_InscrireResultatMatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InscrireResultatMatchActionPerformed(evt);
            }
        });

        jLabel_Court.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Fermer, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_InscrireResultatMatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel_IdMatch))
                                    .addComponent(jLabel_Court))
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel_Heure, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel_Date)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel_IdMatch)
                    .addComponent(jLabel6)
                    .addComponent(jLabel_Date))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel_Heure)
                    .addComponent(jLabel_Court))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_InscrireResultatMatch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Fermer, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void jButton_FermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FermerActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton_FermerActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            this.dispose();
        }
    }//GEN-LAST:event_formKeyPressed

    private void jButton_InscrireResultatMatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InscrireResultatMatchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_InscrireResultatMatchActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Fermer;
    private javax.swing.JButton jButton_InscrireResultatMatch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_ArbitreChaise;
    private javax.swing.JLabel jLabel_ArbitreFilet;
    private javax.swing.JLabel jLabel_Contre;
    private javax.swing.JLabel jLabel_Court;
    private javax.swing.JLabel jLabel_Date;
    private javax.swing.JLabel jLabel_Heure;
    private javax.swing.JLabel jLabel_IdMatch;
    private javax.swing.JLabel jLabel_Joueur1;
    private javax.swing.JLabel jLabel_Joueur2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextArea_ArbitresLigne;
    private javax.swing.JTextArea jTextArea_Ramasseurs1;
    private javax.swing.JTextArea jTextArea_Ramasseurs2;
    // End of variables declaration//GEN-END:variables
}
